/*****************************************************************************/
/********** !!! WARNING: CODE GENERATED BY TAPROOT. DO NOT EDIT !!! **********/
/*****************************************************************************/

/*
 * Copyright (c) 2020-2021 Advanced Robotics at the University of Washington <robomstr@uw.edu>
 *
 * This file is part of Taproot.
 *
 * Taproot is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Taproot is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Taproot.  If not, see <https://www.gnu.org/licenses/>.
 */

#include "math_user_utils.hpp"
#include "modm/math/matrix.hpp"
#include "modm/math/geometry/vector.hpp"

#include <cstdint>

float tap::algorithms::fastInvSqrt(float x)
{
    static_assert(sizeof(float) == 4, "fast inverse sqrt requires 32-bit float");
    float halfx = 0.5f * x;
    float y = x;
    int32_t i = reinterpretCopy<float, int32_t>(y);
    i = 0x5f3759df - (i >> 1);
    y = reinterpretCopy<int32_t, float>(i);
    y = y * (1.5f - (halfx * y * y));
    return y;
}

void tap::algorithms::rotateVector(float* x, float* y, float radians)
{
    float x_temp = *x;
    *x = (*x) * cosf(radians) - *y * sinf(radians);
    *y = x_temp * sinf(radians) + *y * cosf(radians);
}

void tap::algorithms::rotateVector(modm::Vector3f* vec, Rotation r)
{
    float cosAng = cosf(r.yaw);
    float sinAng = sinf(r.yaw);
    float m[9] = {cosAng, -sinAng, 0,
                  sinAng, cosAng, 0,
                  0, 0, 1};
    modm::Matrix3f tf = modm::Matrix3f(m);
    *vec = tf*(*vec);

    cosAng = cosf(r.pitch);
    sinAng = sinf(r.pitch);
    float n[9] = {cosAng, 0, sinAng,
         0, 1, 0,
         -sinAng, 0, cosAng};
    tf = modm::Matrix3f(n);
    *vec = tf*(*vec);

    cosAng = cosf(r.roll);
    sinAng = sinf(r.roll);
    float j[9] = {1, 0, 0,
                  0, cosAng, -sinAng,
                  0, sinAng, cosAng};
    tf = modm::Matrix3f(j);
    *vec = tf*(*vec);
}
