# Copyright (c) 2020-2021 Advanced Robotics at the University of Washington <robomstr@uw.edu>
#
# This file is part of aruw-mcb.
#
# aruw-mcb is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# aruw-mcb is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with aruw-mcb.  If not, see <https://www.gnu.org/licenses/>.


Import("env")

from os.path import abspath, join

VariantDir(
    './segger-rtt',
    '../../segger-rtt',
    duplicate=1
)

env.AppendUnique(CPPPATH=[
    "#/ext/segger-rtt/RTT",
    "#/ext/segger-rtt/Config",
])

newenv = env.Clone()
newenv.Append(CCFLAGS=["-w"]) # suppress all warnings

rtt_sources = [
    abspath(join("segger-rtt", "RTT", "SEGGER_RTT.c")),
    abspath(join("segger-rtt", "RTT", "SEGGER_RTT_printf.c")),
]

library = newenv.StaticLibrary(target="segger-rtt", source=rtt_sources)

env.AppendUnique(LIBS=[
    library,
])

Return("library")
