# Copyright (c) 2020-2021 Advanced Robotics at the University of Washington <robomstr@uw.edu>
#
# This file is part of aruw-mcb.
#
# aruw-mcb is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# aruw-mcb is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with aruw-mcb.  If not, see <https://www.gnu.org/licenses/>.

from build_tools.extract_robot_type import VALID_ROBOT_TYPES
from os.path import join

Import("env")
Import("args")
Import("sources")

IGNORED_ROBOT_TYPE_WORKING_DIRECTORY = "aruwsrc/control"

ignored_files = []
ignored_dirs = []

if args["TARGET_ENV"] == "tests":
    env_cpy = env.Clone()

    # Append on the global robot target build flag
    env_cpy.AppendUnique(CCFLAGS=["-D " + args["ROBOT_TYPE"]])

    if args["COMPILE_SRC"]:
        for robot in VALID_ROBOT_TYPES:
            if robot != args["ROBOT_TYPE"]:
                robot_dir = str.lower(robot)[len("robot_") + 1:]
                ignored_dirs.append(join(IGNORED_ROBOT_TYPE_WORKING_DIRECTORY, robot_dir))

        rawSrcs = env_cpy.FindSourceFiles(".", ignorePaths=ignored_dirs, ignoreFiles=ignored_files)
    else:
        rawSrcs = []

    for source in rawSrcs:
        sources.append(env_cpy.Object(source))

Return('sources')
