/*****************************************************************************/
/********** !!! WARNING: CODE GENERATED BY TAPROOT. DO NOT EDIT !!! **********/
/*****************************************************************************/

#ifndef ANALOG_REMOTE_MAPPING_HPP_
#define ANALOG_REMOTE_MAPPING_HPP_


namespace tap::control
{

class AnalogRemoteMapping
{
public:
    virtual float getValue() const = 0;
};

}

#endif  // ANALOG_REMOTE_MAPPING