/*****************************************************************************/
/********** !!! WARNING: CODE GENERATED BY TAPROOT. DO NOT EDIT !!! **********/
/*****************************************************************************/

/*
 * Copyright (c) 2020-2021 Advanced Robotics at the University of Washington <robomstr@uw.edu>
 *
 * This file is part of Taproot.
 *
 * Taproot is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Taproot is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Taproot.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * Copyright (c) 2015-2018, Niklas Hauser
 * Copyright (c) 2017, Sascha Schade
 * Copyright (c) 2018, Antal Szabó
 *
 * This file is part of the modm project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */
// ----------------------------------------------------------------------------

#ifndef TAPROOT_BOARD_HPP_
#define TAPROOT_BOARD_HPP_

#ifndef PLATFORM_HOSTED
#include "modm/architecture/interface/clock.hpp"
#include "modm/platform.hpp"

using namespace modm::platform;
#else
#include "modm/math/units.hpp"
#endif

namespace Board
{
using namespace modm::literals;

/**
 * STM32F427IIH6 running at 180MHz from the external 12MHz crystal
 */
struct SystemClock
{
    static constexpr uint32_t Frequency = 180_MHz;
    static constexpr uint32_t Ahb = Frequency;
    static constexpr uint32_t Apb1 = Ahb / 4;
    static constexpr uint32_t Apb2 = Ahb / 2;

    static constexpr uint32_t Adc = Apb2;

    static constexpr uint32_t Spi1 = Apb2;
    static constexpr uint32_t Spi4 = Apb2;
    static constexpr uint32_t Spi5 = Apb2;

    static constexpr uint32_t Usart1 = Apb2;
    static constexpr uint32_t Usart2 = Apb1;
    static constexpr uint32_t Usart3 = Apb1;
    static constexpr uint32_t Usart6 = Apb2;
    static constexpr uint32_t Uart7 = Apb1;
    static constexpr uint32_t Uart8 = Apb1;

    static constexpr uint32_t Can1 = Apb1;
    static constexpr uint32_t Can2 = Apb1;

    static constexpr uint32_t I2c2 = Apb1;

    static constexpr uint32_t Apb1Timer = Apb1 * 2;
    static constexpr uint32_t Apb2Timer = Apb2 * 2;
    static constexpr uint32_t Timer2 = Apb1Timer;
    static constexpr uint32_t Timer3 = Apb1Timer;
    static constexpr uint32_t Timer4 = Apb1Timer;
    static constexpr uint32_t Timer5 = Apb1Timer;
    static constexpr uint32_t Timer8 = Apb2Timer;
    static constexpr uint32_t Timer9 = Apb2Timer;
    static constexpr uint32_t Timer12 = Apb1Timer;

    static bool inline enable()
    {
#ifndef PLATFORM_HOSTED
        Rcc::enableExternalCrystal();  // 12 MHz
        Rcc::PllFactors pllF = {
            6,    // 12MHz / M=6 -> 2MHz
            180,  // 2MHz * N=180 -> 360MHz
            2     // 360MHz / P=2 -> 180MHz = F_cpu
        };
        Rcc::enablePll(Rcc::PllSource::ExternalCrystal, pllF);

        Rcc::setFlashLatency<Frequency>();
        Rcc::enableSystemClock(Rcc::SystemClockSource::Pll);
        Rcc::setAhbPrescaler(Rcc::AhbPrescaler::Div1);
        Rcc::setApb1Prescaler(Rcc::Apb1Prescaler::Div4);
        Rcc::setApb2Prescaler(Rcc::Apb2Prescaler::Div2);
        Rcc::updateCoreFrequency<Frequency>();
#endif

        return true;
    }
};

#ifndef PLATFORM_HOSTED


// initialize 9 green Leds and 1 red LED
using LedA = GpioInverted<GpioG8>;
using LedB = GpioInverted<GpioG7>;
using LedC = GpioInverted<GpioG6>;
using LedD = GpioInverted<GpioG5>;
using LedE = GpioInverted<GpioG4>;
using LedF = GpioInverted<GpioG3>;
using LedG = GpioInverted<GpioG2>;
using LedH = GpioInverted<GpioG1>;
using LedGreen = GpioInverted<GpioF14>;
using LedRed = GpioInverted<GpioE11>;
using LedsPort = SoftwareGpioPort<LedA, LedB, LedC, LedD, LedE, LedF, LedG, LedH, LedGreen, LedRed>;

// initialize 4 24V outputs
using PowerOutPort1 = GpioH2;
using PowerOutPort2 = GpioH3;
using PowerOutPort3 = GpioH4;
using PowerOutPort4 = GpioH5;
using PowerOutsPort = SoftwareGpioPort<PowerOutPort1, PowerOutPort2, PowerOutPort3, PowerOutPort4>;


// Initialize analog input pins
using AnalogInPinS = GpioA0;
using AnalogInPinU = GpioA2;
using AnalogInPinV = GpioA3;
using AnalogInPins = SoftwareGpioPort<AnalogInPinS, AnalogInPinU, AnalogInPinV>;

// Initialize PWM pins
using Buzzer = GpioH6;
using PWMOutPinW = GpioI5;
using PWMOutPinX = GpioI6;
using PWMOutPins = SoftwareGpioPort<Buzzer, PWMOutPinW, PWMOutPinX>;

// Initialize digital input pins
using DigitalInPinT = GpioA1;
using Button = GpioB2;
using DigitalInPinD = GpioH10;
using DigitalInPinC = GpioH11;
using DigitalInPinB = GpioH12;
using DigitalInPins = SoftwareGpioPort<DigitalInPinT, Button, DigitalInPinD, DigitalInPinC, DigitalInPinB>;

// Initialize digital output pins
using DigitalOutPinH = GpioD12;
using DigitalOutPinG = GpioD13;
using DigitalOutPinF = GpioD14;
using DigitalOutPinE = GpioD15;
using DigitalOutPinLaser = GpioG13;
using DigitalOutPinZ = GpioI2;
using DigitalOutPinY = GpioI7;
using DigitalOutPins = SoftwareGpioPort<DigitalOutPinH, DigitalOutPinG, DigitalOutPinF, DigitalOutPinE, DigitalOutPinLaser, DigitalOutPinZ, DigitalOutPinY>;


// SPI to the display spi port on the board
using DisplaySck = GpioB3;
using DisplayPoci = GpioB4;
using DisplayPico = GpioA7;
using DisplayReset = GpioB10;
using DisplayCommand = GpioB9;
using DisplayJoystick = GpioA6;
using DisplaySpi = SpiMaster1;

using Ism330Sck = GpioE12;
using Ism330Poci = GpioE5;
using Ism330Pico = GpioE6;
using Ism330Nss = GpioE4;
using Ism330Spi = SpiMaster4;

// SPI for the Mpu6500 IMU on the board
using ImuSck = GpioF7;
using ImuPoci = GpioF8;
using ImuPico = GpioF9;
using ImuNss = GpioF6;
using ImuHeater = GpioB5;
using ImuSpi = SpiMaster5;

using I2c2Sda = GpioF0;
using I2c2Scl = GpioF1;
using I2c2 = I2cMaster2;

#endif

inline void initialize()
{
    // init clock
    SystemClock::enable();
#ifndef PLATFORM_HOSTED
    SysTickTimer::initialize<SystemClock>();
#endif
}

#ifndef PLATFORM_HOSTED

template <uint32_t Baudrate = 10000000>
inline void initializeDisplaySpi()
{
    DisplaySpi::connect<DisplayPoci::Miso, DisplayPico::Mosi, DisplaySck::Sck>();
    DisplaySpi::initialize<SystemClock, Baudrate>();
}

template <uint32_t Baudrate = 10000000>
inline void initializeIsm330Spi()
{
    Ism330Spi::connect<Ism330Poci::Miso, Ism330Pico::Mosi, Ism330Sck::Sck>();
    Ism330Spi::initialize<SystemClock, Baudrate>();
}

template <uint32_t Baudrate = 10000000>
inline void initializeImuSpi()
{
    ImuSpi::connect<ImuPoci::Miso, ImuPico::Mosi, ImuSck::Sck>();
    ImuSpi::initialize<SystemClock, Baudrate>();
}

template <uint32_t Baudrate = 100000>
inline void initializeI2c2(I2c2::PullUps pullups = I2c2::PullUps::Internal)
{
    I2c2::connect<I2c2Scl::Scl, I2c2Sda::Sda>(pullups);
    I2c2::initialize<SystemClock, Baudrate>();
}
#endif

}  // namespace Board

#endif  // TAPROOT_BOARD_HPP_
