#ifndef MENU_IDENTIFIERS_HPP_
#define MENU_IDENTIFIERS_HPP_

#define SPLASH_SCREEN_MENU_ID 1
#define MAIN_MENU_ID 2
#define ERROR_MENU_ID 3
#define HARDWARE_TEST_MENU_ID 4
#define MOTOR_MENU_ID 5
#define MOTOR_SPECIFIC_MENU_ID 6
#define COMMAND_SCHEDULER_MENU_ID 7
#define CV_MENU_ID 8

#endif // MENU_IDENTIFIERS_HPP_